# Từ điển chuẩn hóa từ viết tắt
dictions = {
    "a": "anh",
    "A": "Anh",
    "E": "Em",
    "e": "em",
    "bh": "bây giờ",
    "Bh": "bây giờ",
    "dc": "được",
    "Đc": "được",
    "đc": "được",
    "dr": "đúng rồi",
    "đr": "đúng rồi",
    "dz": "đẹp trai",
    "đz": "đẹp zai",
    "lm": "làm",
    "Lm": "Làm",
    "tr": "trang",
    "khg": "không",
    "khĝ": "không",
    "ko": "không",
    "hok": "không",
    "k": "không",
    "hem": "không",
    "khum": "không",
    "kg": "không",
    "kh": "không",
    "đc": "được",
    "dc": "được",
    "ng": "người",
    "bt": "biết",
    "bik": "biết",
    "hc": "học",
    "vt": "viết",
    "nc": "nước",
    "Nc": "nước",
    "NN": "nhà nước",
    "Nc": "nước",
    "nx": "nữa",
    "Nx": "nữa",
    "cx": "cũng",
    "Cx": "cũng",
    "trc": "trước",
    "j": "gì",
    "bx": "bữa",
    "vg": "vâng",
    "BTC": "ban tổ chức",
    "CLB": "Câu lạc bộ",
    "clb": "câu lạc bộ",
    "HTX": "Hợp tác xã",
    "NXB": "Nhà xuất bản",
    "ÔB": "Ông bà",
    "vn": "Việt Nam",
    "Vn": "Việt Nam",
    "VN": "Việt Nam",
    "TP": "Thành phố",
    "TT": "Tổng thống",
    "TƯ, TW": "Trung ương",
    "UBND": "Ủy ban nhân dân",
    "BCH": "Ban Chấp hành",
    "CHXHCNVN": "Cộng hòa Xã hội Chủ nghĩa Việt Nam",
    "MTDTGPMNVN": "Mặt trận Dân tộc Giải phóng miền Nam Việt Nam",
    "QĐND, QDND": "Quân đội Nhân dân Việt Nam",
    "QLVNCH": "Quân lực Việt Nam Cộng hòa",
    "VNQDĐ, VNQDD": "Việt Nam Quốc dân Đảng",
    "VNCH": "Việt Nam Cộng hòa",
    "VNDCCH": "Việt Nam Dân chủ Cộng hòa",
    "LHQ": "Liên Hợp Quốc",
    "THPT": "Trung học phổ thông",
    "THCS": "Trung học cơ sở",
    "đ/c": "địa chỉ",
    "đc": "địa chỉ",
    "d/c": "địa chỉ",
    "dc": "địa chỉ",
    "k/g": "kính gửi",
    "th/g": "thân gửi",
    "v/v": "về việc",
    "vv": "vân vân",
    "lm": "làm",
    "tr": "trang",
    "khg": "không",
    "khĝ": "không",
    "ko": "không",
    "hok": "không", 
    "k": "không", 
    "hem": "không", 
    "khum": "không", 
    "kg": "không",
    "đc": "được",
    "dc": "được",
    "ng": "người",
    "bik": "biết",
    "kb": "không biết",
    "hc": "học",
    "vt": "viết",
    "trc": "trước",
    "j": "gì",
    "bx": "bữa",
    "vg": "vâng",
    "cty": "công ty",
    "ngta": "người ta",
    "Fahasa": "phát hành sách",
    "Vovinam": "Võ Việt Nam",
    "Xunhasaba": "xuất nhập sách báo"
}
